name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          
      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name my-lambda-function \
            --runtime python3.8 \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://lambda_function.zip \
            --role arn:aws:iam::123456789012:role/lambda-role


      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan -input=false

      - name: Apply Terraform changes
        run: terraform apply -auto-approve 
